namespace: "cutcutfilm-dev"
name: "cutcutfilm-identity-dev"

host: "ccf-dev.vidrox.me"

debug: true

imagePullSecrets: [{ name: cutcutfilm-ghcr }]

persistence:
  claimName: "cutcutfilm-dev-storage"
  mountPath: /app/cutcutfilm-dev/data

services:
  identity:
    replicas: 1
    path: "/identity-service"
    name: "cutcutfilm-identity-dev"
    secretName: "ccf-dev-secret"
    image: ""
    containerPort: 4002
    jwtIssuer: "https://ccf-dev.vidrox.me/identity-service"
    accessTokenTTL: 15 # In minutes
    refreshTokenTTL: 10080 # In minutes
  identityDatabase:
    name: "identity-db-postgresql"
    databaseName: "cutcutfilm-identity"
    secretName: "ccf-dev-secret"
    port: 5433