package environment

const KeysPort = "PORT"
const KeysDebug = "DEBUG"
const KeysEnvironmentType = "ENVIRONMENT_TYPE"
const KeysAppPath = "APP_PATH"
const KeysDataPath = "DATA_PATH"
const KeysTokenIssuer = "JWT_ISSUER"
const KeysAdminID = "ADMIN_ID"
const KeysAdminEmail = "ADMIN_EMAIL"
const KeysAdminUsername = "ADMIN_USERNAME"
const KeysAdminPassword = "ADMIN_PASSWORD"
const KeysDatabaseHost = "DATABASE_URI"
const KeysDatabaseUsername = "POSTGRESQL_USERNAME"
const KeysDatabasePassword = "POSTGRESQL_PASSWORD"
const KeysDatabaseName = "POSTGRESQL_DATABASE"
const KeysDatabasePort = "POSTGRESQL_PORT_NUMBER"
const KeysIdentityServiceLocation = "IDENTITY_SERVICE_LOCATION"
const KeysIdentityServiceApiKey = "IDENTITY_SERVICE_API_KEY"
