apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.services.user.name }}-config
  namespace: {{ .Values.namespace }}
data:
  debug: "{{ .Values.debug }}"
  user_service_database_uri: "{{ .Values.services.userDatabase.name }}.{{ .Values.namespace }}.svc.cluster.local"
  identity_service_location: "http://{{ .Values.services.identity.name }}.{{ .Values.namespace }}.svc.cluster.local:{{ .Values.services.identity.port }}"
