apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.services.user.name }}-config
  namespace: {{ .Values.namespace }}
data:
  user_service_database_uri: "{{ .Values.services.userDatabase.name }}.{{ .Values.namespace }}.svc.cluster.local"
  identity_service_location: "{{ .Values.services.user.identityServiceName }}.{{ .Values.namespace }}.svc.cluster.local:{{ .Values.services.user.identityServicePort }}"
