apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
data:
  user_service_database_uri: "{{ .Values.services.userDatabase.name }}.{{ .Values.namespace }}.svc.cluster.local"
