apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.services.gateway.name }}-config
  namespace: {{ .Values.namespace }}
data:
  identity_service_location: "http://{{ .Values.services.identity.name }}.{{ .Values.namespace }}.svc.cluster.local:{{ .Values.services.identity.port }}"
