apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.gateway.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.services.gateway.name }}
  replicas: {{ .Values.services.gateway.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.services.gateway.name }}
    spec:
      containers:
        - name: {{ .Values.services.gateway.name }}
          image: {{ .Values.services.gateway.image }}
          env:
            - name: PORT
              value: "{{ .Values.services.gateway.containerPort }}"
            - name: DEBUG
              value: "{{ .Values.debug }}"
          ports:
            - containerPort: {{ .Values.services.gateway.containerPort }}
          volumeMounts:
            - name: {{ .Values.persistence.claimName }}
              mountPath: {{ .Values.persistence.mountPath }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: {{ .Values.persistence.claimName }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.claimName }}