FROM golang:1.21.4-bullseye

ENV APP_NAME cutcutfilm
ENV APP_HOME /app/${APP_NAME}/services/user

ARG GIT_USER
ARG GIT_TOKEN

RUN git config --global url."https://${GIT_USER}:${GIT_TOKEN}@github.com".insteadOf "https://github.com"

ENV GO111MODULE=on
ENV GOPRIVATE=github.com/${GIT_USER}/*
ENV CGO_ENABLED=0

WORKDIR "$APP_HOME"

COPY go.mod go.sum ./

RUN go get github.com/githubnemo/CompileDaemon
RUN go install -v github.com/githubnemo/CompileDaemon

RUN go mod tidy

ENTRYPOINT CompileDaemon -polling -build="go build -o tmp/app" -command="tmp/app"