// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: identity/v1/identity.proto

package identityv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/VidroX/cutcutfilm/services/identity/proto/identity/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// IdentityServiceName is the fully-qualified name of the IdentityService service.
	IdentityServiceName = "identity.v1.IdentityService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// IdentityServiceIssueTokensProcedure is the fully-qualified name of the IdentityService's
	// IssueTokens RPC.
	IdentityServiceIssueTokensProcedure = "/identity.v1.IdentityService/IssueTokens"
	// IdentityServiceIssueServiceTokenProcedure is the fully-qualified name of the IdentityService's
	// IssueServiceToken RPC.
	IdentityServiceIssueServiceTokenProcedure = "/identity.v1.IdentityService/IssueServiceToken"
	// IdentityServiceRefreshTokenProcedure is the fully-qualified name of the IdentityService's
	// RefreshToken RPC.
	IdentityServiceRefreshTokenProcedure = "/identity.v1.IdentityService/RefreshToken"
	// IdentityServiceSetUserPermissionsProcedure is the fully-qualified name of the IdentityService's
	// SetUserPermissions RPC.
	IdentityServiceSetUserPermissionsProcedure = "/identity.v1.IdentityService/SetUserPermissions"
	// IdentityServiceGetUserPermissionsProcedure is the fully-qualified name of the IdentityService's
	// GetUserPermissions RPC.
	IdentityServiceGetUserPermissionsProcedure = "/identity.v1.IdentityService/GetUserPermissions"
	// IdentityServiceValidateUserProcedure is the fully-qualified name of the IdentityService's
	// ValidateUser RPC.
	IdentityServiceValidateUserProcedure = "/identity.v1.IdentityService/ValidateUser"
	// IdentityServiceGetKeySetProcedure is the fully-qualified name of the IdentityService's GetKeySet
	// RPC.
	IdentityServiceGetKeySetProcedure = "/identity.v1.IdentityService/GetKeySet"
	// IdentityServiceRevokeTokenProcedure is the fully-qualified name of the IdentityService's
	// RevokeToken RPC.
	IdentityServiceRevokeTokenProcedure = "/identity.v1.IdentityService/RevokeToken"
	// IdentityServiceIsTokenRevokedProcedure is the fully-qualified name of the IdentityService's
	// IsTokenRevoked RPC.
	IdentityServiceIsTokenRevokedProcedure = "/identity.v1.IdentityService/IsTokenRevoked"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	identityServiceServiceDescriptor                  = v1.File_identity_v1_identity_proto.Services().ByName("IdentityService")
	identityServiceIssueTokensMethodDescriptor        = identityServiceServiceDescriptor.Methods().ByName("IssueTokens")
	identityServiceIssueServiceTokenMethodDescriptor  = identityServiceServiceDescriptor.Methods().ByName("IssueServiceToken")
	identityServiceRefreshTokenMethodDescriptor       = identityServiceServiceDescriptor.Methods().ByName("RefreshToken")
	identityServiceSetUserPermissionsMethodDescriptor = identityServiceServiceDescriptor.Methods().ByName("SetUserPermissions")
	identityServiceGetUserPermissionsMethodDescriptor = identityServiceServiceDescriptor.Methods().ByName("GetUserPermissions")
	identityServiceValidateUserMethodDescriptor       = identityServiceServiceDescriptor.Methods().ByName("ValidateUser")
	identityServiceGetKeySetMethodDescriptor          = identityServiceServiceDescriptor.Methods().ByName("GetKeySet")
	identityServiceRevokeTokenMethodDescriptor        = identityServiceServiceDescriptor.Methods().ByName("RevokeToken")
	identityServiceIsTokenRevokedMethodDescriptor     = identityServiceServiceDescriptor.Methods().ByName("IsTokenRevoked")
)

// IdentityServiceClient is a client for the identity.v1.IdentityService service.
type IdentityServiceClient interface {
	IssueTokens(context.Context, *connect.Request[v1.IssueTokensRequest]) (*connect.Response[v1.IssueTokensResponse], error)
	IssueServiceToken(context.Context, *connect.Request[v1.IssueServiceTokenRequest]) (*connect.Response[v1.IssueServiceTokenResponse], error)
	RefreshToken(context.Context, *connect.Request[v1.RefreshTokenRequest]) (*connect.Response[v1.RefreshTokenResponse], error)
	SetUserPermissions(context.Context, *connect.Request[v1.SetUserPermissionsRequest]) (*connect.Response[v1.SetUserPermissionsResponse], error)
	GetUserPermissions(context.Context, *connect.Request[v1.GetUserPermissionsRequest]) (*connect.Response[v1.GetUserPermissionsResponse], error)
	ValidateUser(context.Context, *connect.Request[v1.ValidateUserRequest]) (*connect.Response[v1.ValidateUserResponse], error)
	GetKeySet(context.Context, *connect.Request[v1.GetKeySetRequest]) (*connect.Response[v1.GetKeySetResponse], error)
	RevokeToken(context.Context, *connect.Request[v1.RevokeTokenRequest]) (*connect.Response[v1.RevokeTokenResponse], error)
	IsTokenRevoked(context.Context, *connect.Request[v1.IsTokenRevokedRequest]) (*connect.Response[v1.IsTokenRevokedResponse], error)
}

// NewIdentityServiceClient constructs a client for the identity.v1.IdentityService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewIdentityServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) IdentityServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &identityServiceClient{
		issueTokens: connect.NewClient[v1.IssueTokensRequest, v1.IssueTokensResponse](
			httpClient,
			baseURL+IdentityServiceIssueTokensProcedure,
			connect.WithSchema(identityServiceIssueTokensMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		issueServiceToken: connect.NewClient[v1.IssueServiceTokenRequest, v1.IssueServiceTokenResponse](
			httpClient,
			baseURL+IdentityServiceIssueServiceTokenProcedure,
			connect.WithSchema(identityServiceIssueServiceTokenMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		refreshToken: connect.NewClient[v1.RefreshTokenRequest, v1.RefreshTokenResponse](
			httpClient,
			baseURL+IdentityServiceRefreshTokenProcedure,
			connect.WithSchema(identityServiceRefreshTokenMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		setUserPermissions: connect.NewClient[v1.SetUserPermissionsRequest, v1.SetUserPermissionsResponse](
			httpClient,
			baseURL+IdentityServiceSetUserPermissionsProcedure,
			connect.WithSchema(identityServiceSetUserPermissionsMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getUserPermissions: connect.NewClient[v1.GetUserPermissionsRequest, v1.GetUserPermissionsResponse](
			httpClient,
			baseURL+IdentityServiceGetUserPermissionsProcedure,
			connect.WithSchema(identityServiceGetUserPermissionsMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		validateUser: connect.NewClient[v1.ValidateUserRequest, v1.ValidateUserResponse](
			httpClient,
			baseURL+IdentityServiceValidateUserProcedure,
			connect.WithSchema(identityServiceValidateUserMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getKeySet: connect.NewClient[v1.GetKeySetRequest, v1.GetKeySetResponse](
			httpClient,
			baseURL+IdentityServiceGetKeySetProcedure,
			connect.WithSchema(identityServiceGetKeySetMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		revokeToken: connect.NewClient[v1.RevokeTokenRequest, v1.RevokeTokenResponse](
			httpClient,
			baseURL+IdentityServiceRevokeTokenProcedure,
			connect.WithSchema(identityServiceRevokeTokenMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		isTokenRevoked: connect.NewClient[v1.IsTokenRevokedRequest, v1.IsTokenRevokedResponse](
			httpClient,
			baseURL+IdentityServiceIsTokenRevokedProcedure,
			connect.WithSchema(identityServiceIsTokenRevokedMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// identityServiceClient implements IdentityServiceClient.
type identityServiceClient struct {
	issueTokens        *connect.Client[v1.IssueTokensRequest, v1.IssueTokensResponse]
	issueServiceToken  *connect.Client[v1.IssueServiceTokenRequest, v1.IssueServiceTokenResponse]
	refreshToken       *connect.Client[v1.RefreshTokenRequest, v1.RefreshTokenResponse]
	setUserPermissions *connect.Client[v1.SetUserPermissionsRequest, v1.SetUserPermissionsResponse]
	getUserPermissions *connect.Client[v1.GetUserPermissionsRequest, v1.GetUserPermissionsResponse]
	validateUser       *connect.Client[v1.ValidateUserRequest, v1.ValidateUserResponse]
	getKeySet          *connect.Client[v1.GetKeySetRequest, v1.GetKeySetResponse]
	revokeToken        *connect.Client[v1.RevokeTokenRequest, v1.RevokeTokenResponse]
	isTokenRevoked     *connect.Client[v1.IsTokenRevokedRequest, v1.IsTokenRevokedResponse]
}

// IssueTokens calls identity.v1.IdentityService.IssueTokens.
func (c *identityServiceClient) IssueTokens(ctx context.Context, req *connect.Request[v1.IssueTokensRequest]) (*connect.Response[v1.IssueTokensResponse], error) {
	return c.issueTokens.CallUnary(ctx, req)
}

// IssueServiceToken calls identity.v1.IdentityService.IssueServiceToken.
func (c *identityServiceClient) IssueServiceToken(ctx context.Context, req *connect.Request[v1.IssueServiceTokenRequest]) (*connect.Response[v1.IssueServiceTokenResponse], error) {
	return c.issueServiceToken.CallUnary(ctx, req)
}

// RefreshToken calls identity.v1.IdentityService.RefreshToken.
func (c *identityServiceClient) RefreshToken(ctx context.Context, req *connect.Request[v1.RefreshTokenRequest]) (*connect.Response[v1.RefreshTokenResponse], error) {
	return c.refreshToken.CallUnary(ctx, req)
}

// SetUserPermissions calls identity.v1.IdentityService.SetUserPermissions.
func (c *identityServiceClient) SetUserPermissions(ctx context.Context, req *connect.Request[v1.SetUserPermissionsRequest]) (*connect.Response[v1.SetUserPermissionsResponse], error) {
	return c.setUserPermissions.CallUnary(ctx, req)
}

// GetUserPermissions calls identity.v1.IdentityService.GetUserPermissions.
func (c *identityServiceClient) GetUserPermissions(ctx context.Context, req *connect.Request[v1.GetUserPermissionsRequest]) (*connect.Response[v1.GetUserPermissionsResponse], error) {
	return c.getUserPermissions.CallUnary(ctx, req)
}

// ValidateUser calls identity.v1.IdentityService.ValidateUser.
func (c *identityServiceClient) ValidateUser(ctx context.Context, req *connect.Request[v1.ValidateUserRequest]) (*connect.Response[v1.ValidateUserResponse], error) {
	return c.validateUser.CallUnary(ctx, req)
}

// GetKeySet calls identity.v1.IdentityService.GetKeySet.
func (c *identityServiceClient) GetKeySet(ctx context.Context, req *connect.Request[v1.GetKeySetRequest]) (*connect.Response[v1.GetKeySetResponse], error) {
	return c.getKeySet.CallUnary(ctx, req)
}

// RevokeToken calls identity.v1.IdentityService.RevokeToken.
func (c *identityServiceClient) RevokeToken(ctx context.Context, req *connect.Request[v1.RevokeTokenRequest]) (*connect.Response[v1.RevokeTokenResponse], error) {
	return c.revokeToken.CallUnary(ctx, req)
}

// IsTokenRevoked calls identity.v1.IdentityService.IsTokenRevoked.
func (c *identityServiceClient) IsTokenRevoked(ctx context.Context, req *connect.Request[v1.IsTokenRevokedRequest]) (*connect.Response[v1.IsTokenRevokedResponse], error) {
	return c.isTokenRevoked.CallUnary(ctx, req)
}

// IdentityServiceHandler is an implementation of the identity.v1.IdentityService service.
type IdentityServiceHandler interface {
	IssueTokens(context.Context, *connect.Request[v1.IssueTokensRequest]) (*connect.Response[v1.IssueTokensResponse], error)
	IssueServiceToken(context.Context, *connect.Request[v1.IssueServiceTokenRequest]) (*connect.Response[v1.IssueServiceTokenResponse], error)
	RefreshToken(context.Context, *connect.Request[v1.RefreshTokenRequest]) (*connect.Response[v1.RefreshTokenResponse], error)
	SetUserPermissions(context.Context, *connect.Request[v1.SetUserPermissionsRequest]) (*connect.Response[v1.SetUserPermissionsResponse], error)
	GetUserPermissions(context.Context, *connect.Request[v1.GetUserPermissionsRequest]) (*connect.Response[v1.GetUserPermissionsResponse], error)
	ValidateUser(context.Context, *connect.Request[v1.ValidateUserRequest]) (*connect.Response[v1.ValidateUserResponse], error)
	GetKeySet(context.Context, *connect.Request[v1.GetKeySetRequest]) (*connect.Response[v1.GetKeySetResponse], error)
	RevokeToken(context.Context, *connect.Request[v1.RevokeTokenRequest]) (*connect.Response[v1.RevokeTokenResponse], error)
	IsTokenRevoked(context.Context, *connect.Request[v1.IsTokenRevokedRequest]) (*connect.Response[v1.IsTokenRevokedResponse], error)
}

// NewIdentityServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewIdentityServiceHandler(svc IdentityServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	identityServiceIssueTokensHandler := connect.NewUnaryHandler(
		IdentityServiceIssueTokensProcedure,
		svc.IssueTokens,
		connect.WithSchema(identityServiceIssueTokensMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	identityServiceIssueServiceTokenHandler := connect.NewUnaryHandler(
		IdentityServiceIssueServiceTokenProcedure,
		svc.IssueServiceToken,
		connect.WithSchema(identityServiceIssueServiceTokenMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	identityServiceRefreshTokenHandler := connect.NewUnaryHandler(
		IdentityServiceRefreshTokenProcedure,
		svc.RefreshToken,
		connect.WithSchema(identityServiceRefreshTokenMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	identityServiceSetUserPermissionsHandler := connect.NewUnaryHandler(
		IdentityServiceSetUserPermissionsProcedure,
		svc.SetUserPermissions,
		connect.WithSchema(identityServiceSetUserPermissionsMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	identityServiceGetUserPermissionsHandler := connect.NewUnaryHandler(
		IdentityServiceGetUserPermissionsProcedure,
		svc.GetUserPermissions,
		connect.WithSchema(identityServiceGetUserPermissionsMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	identityServiceValidateUserHandler := connect.NewUnaryHandler(
		IdentityServiceValidateUserProcedure,
		svc.ValidateUser,
		connect.WithSchema(identityServiceValidateUserMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	identityServiceGetKeySetHandler := connect.NewUnaryHandler(
		IdentityServiceGetKeySetProcedure,
		svc.GetKeySet,
		connect.WithSchema(identityServiceGetKeySetMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	identityServiceRevokeTokenHandler := connect.NewUnaryHandler(
		IdentityServiceRevokeTokenProcedure,
		svc.RevokeToken,
		connect.WithSchema(identityServiceRevokeTokenMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	identityServiceIsTokenRevokedHandler := connect.NewUnaryHandler(
		IdentityServiceIsTokenRevokedProcedure,
		svc.IsTokenRevoked,
		connect.WithSchema(identityServiceIsTokenRevokedMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/identity.v1.IdentityService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case IdentityServiceIssueTokensProcedure:
			identityServiceIssueTokensHandler.ServeHTTP(w, r)
		case IdentityServiceIssueServiceTokenProcedure:
			identityServiceIssueServiceTokenHandler.ServeHTTP(w, r)
		case IdentityServiceRefreshTokenProcedure:
			identityServiceRefreshTokenHandler.ServeHTTP(w, r)
		case IdentityServiceSetUserPermissionsProcedure:
			identityServiceSetUserPermissionsHandler.ServeHTTP(w, r)
		case IdentityServiceGetUserPermissionsProcedure:
			identityServiceGetUserPermissionsHandler.ServeHTTP(w, r)
		case IdentityServiceValidateUserProcedure:
			identityServiceValidateUserHandler.ServeHTTP(w, r)
		case IdentityServiceGetKeySetProcedure:
			identityServiceGetKeySetHandler.ServeHTTP(w, r)
		case IdentityServiceRevokeTokenProcedure:
			identityServiceRevokeTokenHandler.ServeHTTP(w, r)
		case IdentityServiceIsTokenRevokedProcedure:
			identityServiceIsTokenRevokedHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedIdentityServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedIdentityServiceHandler struct{}

func (UnimplementedIdentityServiceHandler) IssueTokens(context.Context, *connect.Request[v1.IssueTokensRequest]) (*connect.Response[v1.IssueTokensResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("identity.v1.IdentityService.IssueTokens is not implemented"))
}

func (UnimplementedIdentityServiceHandler) IssueServiceToken(context.Context, *connect.Request[v1.IssueServiceTokenRequest]) (*connect.Response[v1.IssueServiceTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("identity.v1.IdentityService.IssueServiceToken is not implemented"))
}

func (UnimplementedIdentityServiceHandler) RefreshToken(context.Context, *connect.Request[v1.RefreshTokenRequest]) (*connect.Response[v1.RefreshTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("identity.v1.IdentityService.RefreshToken is not implemented"))
}

func (UnimplementedIdentityServiceHandler) SetUserPermissions(context.Context, *connect.Request[v1.SetUserPermissionsRequest]) (*connect.Response[v1.SetUserPermissionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("identity.v1.IdentityService.SetUserPermissions is not implemented"))
}

func (UnimplementedIdentityServiceHandler) GetUserPermissions(context.Context, *connect.Request[v1.GetUserPermissionsRequest]) (*connect.Response[v1.GetUserPermissionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("identity.v1.IdentityService.GetUserPermissions is not implemented"))
}

func (UnimplementedIdentityServiceHandler) ValidateUser(context.Context, *connect.Request[v1.ValidateUserRequest]) (*connect.Response[v1.ValidateUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("identity.v1.IdentityService.ValidateUser is not implemented"))
}

func (UnimplementedIdentityServiceHandler) GetKeySet(context.Context, *connect.Request[v1.GetKeySetRequest]) (*connect.Response[v1.GetKeySetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("identity.v1.IdentityService.GetKeySet is not implemented"))
}

func (UnimplementedIdentityServiceHandler) RevokeToken(context.Context, *connect.Request[v1.RevokeTokenRequest]) (*connect.Response[v1.RevokeTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("identity.v1.IdentityService.RevokeToken is not implemented"))
}

func (UnimplementedIdentityServiceHandler) IsTokenRevoked(context.Context, *connect.Request[v1.IsTokenRevokedRequest]) (*connect.Response[v1.IsTokenRevokedResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("identity.v1.IdentityService.IsTokenRevoked is not implemented"))
}
