apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.services.identity.name }}-config
  namespace: {{ .Values.namespace }}
data:
  debug: "{{ .Values.debug }}"
  identity_service_database_uri: "{{ .Values.services.identityDatabase.name }}.{{ .Values.namespace }}.svc.cluster.local"
  jwt_issuer: "{{ .Values.services.identity.jwtIssuer }}"
