apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.identity.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.services.identity.name }}
  replicas: {{ .Values.services.identity.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.services.identity.name }}
    spec:
      containers:
        - name: {{ .Values.services.identity.name }}
          image: {{ .Values.services.identity.image }}
          env:
            - name: PORT
              value: "{{ .Values.services.identity.containerPort }}"
            - name: DEBUG
              value: "{{ .Values.debug }}"
            - name: DATABASE_URI
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.services.identity.name }}-config
                  key: identity_service_database_uri
            - name: POSTGRESQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.services.identityDatabase.secretName }}
                  key: identity-db-username
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.services.identityDatabase.secretName }}
                  key: identity-db-password
            - name: POSTGRESQL_DATABASE
              value: "{{ .Values.services.identityDatabase.databaseName }}"
            - name: POSTGRESQL_PORT_NUMBER
              value: "{{ .Values.services.identityDatabase.port }}"
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.services.identity.secretName }}
                  key: identity-api-key
            - name: ADMIN_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.services.identity.secretName }}
                  key: admin-id
          ports:
            - containerPort: {{ .Values.services.identity.containerPort }}
          volumeMounts:
            - name: {{ .Values.persistence.claimName }}
              mountPath: {{ .Values.persistence.mountPath }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: {{ .Values.persistence.claimName }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.claimName }}