apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.identity.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.services.identity.containerPort }}
      protocol: TCP
  selector:
    app: {{ .Values.services.identity.name }}