package environment

const KeysPort = "PORT"
const KeysDebug = "DEBUG"
const KeysEnvironmentType = "ENVIRONMENT_TYPE"
const KeysAppPath = "APP_PATH"
const KeysDataPath = "DATA_PATH"
const KeysTokenIssuer = "JWT_ISSUER"
const KeysDatabaseUsername = "POSTGRESQL_USERNAME"
const KeysDatabasePassword = "POSTGRESQL_PASSWORD"
const KeysDatabaseName = "POSTGRESQL_DATABASE"
const KeysDatabasePort = "POSTGRESQL_PORT_NUMBER"
const KeysAPIKey = "API_KEY"
const KeysAdminID = "ADMIN_ID"
const KeysDatabaseHost = "DATABASE_URI"
