namespace: "cutcutfilm-dev"
name: "cutcutfilm-user-dev"

debug: false

imagePullSecrets: [{ name: cutcutfilm-ghcr }]

persistence:
  claimName: "cutcutfilm-dev-storage"
  mountPath: /app/cutcutfilm-dev/data

services:
  user:
    replicas: 1
    name: "cutcutfilm-user-dev"
    image: ""
    containerPort: 4001
  identity:
    name: "cutcutfilm-identity-dev"
    port: 4002
  userDatabase:
    name: "user-db-postgresql"
    secretName: "ccf-dev-secret"
    port: 5432