namespace: "cutcutfilm"
name: "cutcutfilm-user"

host: "cutcutfilm.com"

debug: false

imagePullSecrets: [{ name: cutcutfilm-ghcr }]

persistence:
  claimName: "cutcutfilm-storage"
  mountPath: /app/cutcutfilm/data

services:
  user:
    replicas: 1
    path: "/user-service"
    name: "cutcutfilm-user"
    identityServiceName: "cutcutfilm-identity"
    identityServicePort: 4002
    image: ""
    containerPort: 4001
  userDatabase:
    name: "user-db-postgresql"
    secretName: "ccf-secret"
    port: 5432