// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/VidroX/cutcutfilm-shared/pagination"
	"github.com/VidroX/cutcutfilm-shared/tokens"
)

// Input with the new Permissions to set for the given userId
type SetUserPermissionsInput struct {
	UserID      string    `json:"userId"`
	Permissions []*string `json:"permissions"`
}

// Auth token
type Token struct {
	Type  tokens.TokenType `json:"type"`
	Token string           `json:"token"`
}

// Registration input data for User
type UserRegistrationInput struct {
	UserName string `json:"userName"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

// Response with User and its auth tokens
type UserWithToken struct {
	User         *User  `json:"user,omitempty"`
	AccessToken  *Token `json:"accessToken,omitempty"`
	RefreshToken *Token `json:"refreshToken,omitempty"`
}

// Users list connection
type UsersConnection struct {
	Node     []*User              `json:"node"`
	PageInfo *pagination.PageInfo `json:"pageInfo"`
}
