name: User Service Build and Deploy (DEV)

on:
  push:
    branches: ["dev"]
    paths:
      - "services/user/**"
      - ".github/workflows/user-service-deploy-dev.yaml"
      - "helm/cutcutfilm-user/**"
  workflow_dispatch:

env:
  WORKING_DIRECTORY: "./services/user"
  IMAGE_NAME: "ghcr.io/vidrox/cutcutfilm-user:dev"
  RELEASE_NAME: "cutcutfilm-user"
  NAMESPACE: "cutcutfilm-dev"
  CHART_LOCATION: helm/cutcutfilm-user

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: development
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - uses: actions/checkout@v3
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GIT_REGISTRY_TOKEN }}

      - name: Build and push the Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          context: ${{ env.WORKING_DIRECTORY }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            GIT_USER=${{ secrets.GIT_USER }}
            GIT_TOKEN=${{ secrets.GIT_TOKEN }}
          tags: |
            ${{ env.IMAGE_NAME }}-latest
            ${{ env.IMAGE_NAME }}-${{ github.sha }}

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    environment: development
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to cluster
        uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: helm upgrade ${{ env.RELEASE_NAME }} ${{ env.CHART_LOCATION }}/ --install --wait --atomic --namespace=${{ env.NAMESPACE }} --values=${{ env.CHART_LOCATION }}/values-dev.yaml --set services.user.image=${{ env.IMAGE_NAME }}-${{ github.sha }}
          kubeconfig: '${{ secrets.KUBECONFIG }}'
          overrule_existing_kubeconfig: "true"
  
  rebuild-gateway:
    name: Gateway Service
    needs: deploy
    permissions:
      actions: read
      contents: read
      id-token: write
      packages: write
    uses: ./.github/workflows/gateway-service-deploy-dev.yaml